set serveroutput on;
execute insertarempleados('258','REY GARCIA, RAUL');
execute insertarempleados('150','SAAVEDRA REBOREDO, JORGE');
execute insertarempleados('432','LOBOS OLATE, XIMENA GIOVANNA');
execute insertarempleados('75','CASTAÑEDA BELLIDO, LIDIA');
execute insertarempleados('80','ACUÑA BECERRA, RICARDO');
execute insertarempleados('85','MARTINEZ DIEZ, JOSE LUIS');
execute insertarempleados('91','GARCIA SAENZ, ALEJANDRO');
execute insertarempleados('104','GARCIA SAENZ, NICOLAS');
execute insertarempleados('152','BLANCO ANTUNEZ, RAFAEL');
execute insertarempleados('246','FUENTES PERDIGUERO, CARLOS');
execute insertarempleados('288','MANOTAS PLAZA, SERGIO');
execute insertarempleados('73','SANCHEZ LOBATO, ALEJANDRA');
execute insertarempleados('83','MAESTRE VAZQUEZ, Mª JOSE');
execute insertarempleados('87','TRIGO GOMEZ, MIGUEL');
execute insertarempleados('95','NOVELLA REGAJO, JOSE MARIA');
execute insertarempleados('371','FERNANDEZ MARIN, MARIA JESUS');
execute insertarempleados('536','STEGENA, IVAN');
execute insertarempleados('543','ROMERO GAMERO, JESUS');
execute insertarempleados('552','FERNANDEZ LARA, LAURA');
execute insertarempleados('257','RECIO JIMENEZ, REBECA');
execute insertarempleados('74','SOTO BOTELLA, CARMEN MARIA');
execute insertarempleados('76','RUIZ POPOLIZIO, SHELAH');
execute insertarempleados('79','MORON DIAZ, ALFONSO MANUEL');
execute insertarempleados('92','GUERRERO PALMERO, JOSE MANUEL');
execute insertarempleados('692','GONZALEZ SUAREZ, ROCIO');
execute insertarempleados('159','BENITO SANCHEZ, ALFONSO JAVIER');
execute insertarempleados('51','ASPERA GOMEZ, JOSE MANUEL');
execute insertarempleados('127','MARTIN FERNANDEZ, JOSE ANTONIO');
execute insertarempleados('237','GIMENO MACHETTI, MARIA');
execute insertarempleados('133','ZAHN PALMA, CARLOS ALBERTO');
execute insertarempleados('134','RUBIO GUTIERREZ, SERGIO');
execute insertarempleados('137','CARRILLO ASENSIO, RAQUEL');
execute insertarempleados('139','ESPINOS DEL POZO, SERGIO');
execute insertarempleados('235','GALLEGO VARELA, VERONICA');
execute insertarempleados('236','GARCIA MARMOL, DAVID');
execute insertarempleados('240','RAMIREZ MONTES, NOELIA');
execute insertarempleados('292','GARCIA BRAÑA, MANUELA');
execute insertarempleados('141','WILSON FLORES, DAVID');
execute insertarempleados('142','ESPINOSA ZUMAQUERO, EVA');
execute insertarempleados('148','MOLINA RUIZ, FRANCISCO JAVIER');
execute insertarempleados('242','BLANCO FUERTES, HECTOR');
execute insertarempleados('255','PARIS FERNANDEZ, ALEJANDRO');
execute insertarempleados('0','JEFE MESA NO ASIGNADO');
execute insertarempleados('1','CRUPIER NO ASIGNADO');
