set serveroutput on;
execute insertarjugadores('4','CARBALLO RIVERO, JUAN LUIS');
execute insertarjugadores('38','DE LA INFIESTA DE ASPE, FILOMENO');
execute insertarjugadores('146','DIAZ BRAVO, ANTONIO');
execute insertarjugadores('165','GRACIA DIAZ, MILAGROS');
execute insertarjugadores('167','IZQUIERDO NUÑEZ, CARLOS');
execute insertarjugadores('174','GARCIA JAPON, MANUEL');
execute insertarjugadores('183','RODRIGUEZ DORADO, FEDERICO DAVID');
execute insertarjugadores('207','DOMINGUEZ FOMBELLA, CELEDONIO');
execute insertarjugadores('353','ESQUINAS BARBARA, MIGUEL');
execute insertarjugadores('357','GAONA MOLINA, BALDOMERO');
execute insertarjugadores('425','CORDERO MORENO, JOSE LUIS');
execute insertarjugadores('429','LUQUIÑO SILVA, JOSE ANTONIO');
execute insertarjugadores('447','HERNANDEZ PINZON GARCIA GERALDO, JOSE ALFONSO');
execute insertarjugadores('462','ARTEAGA CALERO, MARIA CONCEPCION');
execute insertarjugadores('572','ARENAS AGUILERA, RAFAEL');
execute insertarjugadores('599','MARTIN MUÑIZ, OBDULIA');
execute insertarjugadores('684','PORCUNA CHAVARRIA, EDUARDO');
execute insertarjugadores('694','MALDONADO CATALAN, CARLOS LUIS');
execute insertarjugadores('704','BONILLA SALVAT, DAVID');
execute insertarjugadores('705','PALMA TOCINO, SEBASTIAN');
execute insertarjugadores('760','CASTAÑO MORERA, FRANCISCO');
execute insertarjugadores('768','TRIGO ROMAN, JOSE FRANCISCO');
execute insertarjugadores('846','DONG, LIFANG');
execute insertarjugadores('867','HU, HAIBIN');
execute insertarjugadores('868','ZHU, CHAO YONG');
execute insertarjugadores('882','ZHU, QUNLIANG');
execute insertarjugadores('911','ESCOBAR ORTIZ, JORGE');
execute insertarjugadores('918','LOPEZ GALAN, EMILIO');
execute insertarjugadores('925','VAZQUEZ MORENO, FRANCISCO JAVIER');
execute insertarjugadores('938','ESPINAR CABAS, MIGUEL ANGEL');
execute insertarjugadores('939','MAYA MAYA, GONZALO');
execute insertarjugadores('953','HEREDIA HEREDIA, PEDRO');
execute insertarjugadores('963','ROMERO GIL, PEDRO');
execute insertarjugadores('968','MARTIN AGUILAR, ANTONIO');
execute insertarjugadores('970','RODRIGUEZ MOHAMED, DAVID');
execute insertarjugadores('1027','VEIGA, MONICA CRISTINA ANTUNES');
execute insertarjugadores('1130','CUEVAS DELGADO, JOSE');
execute insertarjugadores('1163','GONZALEZ MUÑOZ, FRANCISCO');
execute insertarjugadores('1181','GARCIA PEREZ, JOSE MANUEL');
execute insertarjugadores('1182','FERNANDEZ DOMINGUEZ, MANUEL');
execute insertarjugadores('1183','GUTIERREZ NAVARRO, MANUEL JESUS DE LA PASION');
execute insertarjugadores('1213','SOSPEDRA BORREDA, CARLOS');
execute insertarjugadores('1216','JIMENEZ BORJA, MANUEL');
execute insertarjugadores('1287','WANG, YUE');
execute insertarjugadores('1319','IBRAHIM MOUSSA, KHALIL');
execute insertarjugadores('1579','PEREZ LORENZO, JOSE LUIS');
execute insertarjugadores('1674','TORRES FOQRI, JOSE CARLOS');
execute insertarjugadores('1722','VASSIA, FABIAN');
execute insertarjugadores('1792','GARRIDO REPETO, LEONARDO');
execute insertarjugadores('2048','GONZALEZ VEGA, ANTONIO');
execute insertarjugadores('2364','JIMENEZ BEJINES, SANDRO MANUEL');
execute insertarjugadores('2406','PABON BELLVER, MARIA DOLORES');
execute insertarjugadores('2445','LISARDO JIMENEZ, GONZALO ANTONIO');
execute insertarjugadores('2589','CARRETON SERRANO, ROBERTO');
execute insertarjugadores('2701','VILLAFUERTE DE ANCA, MANUEL');
execute insertarjugadores('2734','GALINDO MARTINEZ, CARMELO');
execute insertarjugadores('2906','RUBIO GONZALEZ, ISRAEL');
execute insertarjugadores('2967','VIZARRAGA LOZANO, DAVID');
execute insertarjugadores('3036','CRESPO CAMPON, ANTONIO');
execute insertarjugadores('3093','RAMOS SOLIS, JOSE LUIS');
execute insertarjugadores('3142','CHEN, LINMIN');
execute insertarjugadores('3292','PALMERO BECERRA, JOSE MIGUEL');
execute insertarjugadores('3372','PELIZZA, LEANDRO OSVALDO');
execute insertarjugadores('4542','MARTINEZ BARRAGAN, JUAN MIGUEL');
execute insertarjugadores('4709','FERRERA LOZANO, FRANCISCO JAVIER');
execute insertarjugadores('4743','PEREZ ALFARO, EMILIO');
execute insertarjugadores('4875','VILLAGRAN NUÑEZ, JUAN BOSCO');
execute insertarjugadores('4965','CHEN, LI GUANG');
execute insertarjugadores('5329','ROJAS LOPEZ, ANTONIO');
execute insertarjugadores('5351','CASTAÑO ROMANO, JOSE MANUEL');
execute insertarjugadores('5355','MONTES MORAL, ANTONIO');
execute insertarjugadores('5461','MESEGUER DIAZ, JERONIMO');
execute insertarjugadores('5678','FERNANDEZ CUELLO, JOSE LUIS');
execute insertarjugadores('5943','ENTRENA GARCIA, ANTONIO');
execute insertarjugadores('6343','RUBIO MARTINEZ, IGNACIO');
execute insertarjugadores('6459','HAYLER LOPEZ, JOSE ULF');
execute insertarjugadores('6499','ESCUDERO DELGADO, MARCIAL');
execute insertarjugadores('6595','RODRIGUEZ FERNANDEZ BERMEJO, PAULO CESAR');
execute insertarjugadores('6649','JIN, GUANCHENG');
execute insertarjugadores('6706','PELAEZ NOGUEROL, EDUARDO');
execute insertarjugadores('6741','SORIA PALACIOS, FRANCISCO');
execute insertarjugadores('6794','SANCHEZ RAMOS, ANTONIO VICTOR');
execute insertarjugadores('6920','QUESADA DE LA FLOR, FERNANDO');
execute insertarjugadores('6981','HERNANDEZ MENDEZ, ANTONIO');
execute insertarjugadores('7270','CONTRERAS RODRIGUEZ, JOSE');
execute insertarjugadores('7609','CARRANZA VILALLONGA, MERCEDES');
execute insertarjugadores('7626','ROMERO GALINDO, FRANCISCO JOSE');
execute insertarjugadores('8018','TEJERA AYALA, JOSE JOAQUIN');
execute insertarjugadores('8139','YE, TINGJIAN');
execute insertarjugadores('8286','CADORIO FERREIRA LINO, JOSE FRANCISCO');
execute insertarjugadores('8327','REYES RIVARES, ALBERTO');
execute insertarjugadores('9997','RODRIGUEZ PASTOR, FRANCISCO JAVIER');
execute insertarjugadores('10191','RIVAS MARTINEZ, MANUEL');
execute insertarjugadores('10261','ASIAN LAMA, JOSE ANTONIO');
execute insertarjugadores('10976','SALAS SANCHEZ, JOSE ANTONIO');
execute insertarjugadores('11136','ARANGUEZ CORTES, TOMAS');
execute insertarjugadores('11976','HAYA ZURITA, ALVARO');
execute insertarjugadores('12056','ORTIZ JIMENEZ, FRANCISCO');
execute insertarjugadores('12091','PORTILLO VILCHES, JORGE');
execute insertarjugadores('12180','SANCHEZ MARTIN, MIGUEL ANGEL');
execute insertarjugadores('12252','GONZALEZ DE LA FUENTE, FRANCISCO JAVIER');
execute insertarjugadores('13104','GARCIA ZAPATA, FRANCISCO');
execute insertarjugadores('13348','OJEDA SANTOS, ANTONIO');
execute insertarjugadores('13766','DURAN PARIAS, JOSE MANUEL');
execute insertarjugadores('14162','YAO, LONGZHEN');
execute insertarjugadores('14163','LI, YONGCHUAN');
execute insertarjugadores('14172','CALERO CORREA, JUAN LUIS');
execute insertarjugadores('15085','DIAZ REYES, MANUEL');
execute insertarjugadores('15192','CANTALAPIEDRA PEREYRA, JOSE MANUEL');
execute insertarjugadores('15469','MENDOZA BARROSO, RAFAEL');
execute insertarjugadores('15584','ANDREU COVARRUBIAS, FRANCISCO JAVIER');
execute insertarjugadores('16504','ESTEVEZ VEGA, ROBERTO');
execute insertarjugadores('16795','LLACER SANTOS, AGUSTIN');
execute insertarjugadores('17271','MONTES ESPINOSA, FERNANDO FRANCISCO');
execute insertarjugadores('17748','MIRANDA MOYANO, ANTONIO');
execute insertarjugadores('17882','GARCIA MARTINEZ, ANGEL');
execute insertarjugadores('17969','GOMEZ COSTAS, ISABELO');
execute insertarjugadores('19112','MORALES PEREZ, CARLOS');
execute insertarjugadores('19242','GARCIA FERNANDEZ, JOSE');
execute insertarjugadores('19423','MIAO, ZEEN');
execute insertarjugadores('19499','MARCA JULIA, MARIA ANTONIA');
execute insertarjugadores('19843','BONILLA PRADAS, ABEL');
execute insertarjugadores('20006','BRAVO TARDAGUILA, RAMON');
execute insertarjugadores('20064','CORTES VARGAS, VICENTE');
execute insertarjugadores('20066','SANCHEZ MARZO, MIGUEL');
execute insertarjugadores('21411','ALES NUÑEZ, LEOPOLDO');
execute insertarjugadores('21468','DIEGO GARCIA, ALVARO');
execute insertarjugadores('21469','GARCIA CASTILLO, FRANCISCO JAVIER');
execute insertarjugadores('21506','BELMONTE CORRAL, CRISTOBAL');
execute insertarjugadores('21552','GARRIDO GARCIA, JUAN ANTONIO');
execute insertarjugadores('21553','MERCHANTE GONZALEZ, FRANCISCO MANUEL');
execute insertarjugadores('21766','MORALES CAPITA, CRISTOBAL ANDRES');
execute insertarjugadores('21774','JIMENEZ VERGARA, DANIEL ANGEL');
execute insertarjugadores('21843','JIN, BIAO');
execute insertarjugadores('21967','PEREZ CACHO, LUIS ALBERTO');
execute insertarjugadores('22578','NIETO MARTIN, JOSE MARIA');
execute insertarjugadores('22622','ENRI GARCIA, BLANCA');
execute insertarjugadores('22684','GARCIA, JUAN MANUEL');
execute insertarjugadores('23124','HERRERA LOPEZ, MANUEL');
execute insertarjugadores('23633','RANEDO ADAME, MANUEL JESUS');
execute insertarjugadores('23995','MARTIN SANCHEZ, OSCAR');
execute insertarjugadores('24139','RUIZ RUIZ, JOSE ANGEL');
execute insertarjugadores('24649','YANG, ZIJUN');
execute insertarjugadores('24859','LI, XIGUAN');
execute insertarjugadores('24876','CHACON MARIN, DIEGO JOSE');
execute insertarjugadores('25475','SERRANO CHICA, FRANCISCO DAVID');
execute insertarjugadores('25493','ALONSO BERNAL, PEDRO JOSE');
execute insertarjugadores('25997','GARCIA PEREZ, MANUEL');
execute insertarjugadores('26058','MUÑOZ GALLARDO, JOSE ANTONIO');
execute insertarjugadores('26228','GONZALEZ VAZ, MANUEL');
execute insertarjugadores('26700','ESLAVA LOPEZ, MARION KARINA');
execute insertarjugadores('27695','LI, HANG');
execute insertarjugadores('27939','TIRADO MARIN, FRANCISCO MANUEL');
execute insertarjugadores('28170','PEREZ SAENZ, JOSE LUIS');
execute insertarjugadores('28908','LIN, GUOZENG');
execute insertarjugadores('31169','SALAMANCA MACIAS, MANUEL');
execute insertarjugadores('31194','SANCHEZ ARJONA VALLS, LUIS');
execute insertarjugadores('32676','BLANCO LOBATON, ALFONSO');
execute insertarjugadores('33015','MORA DURAN, FERNANDO');
execute insertarjugadores('33494','RUBIO VALGAÑON, FELIX');
execute insertarjugadores('35295','MATEOS DE PORRAS LARA, CARLOS JAVIER');
execute insertarjugadores('36516','LEBRON GUTIERREZ, DAVID');
execute insertarjugadores('36981','ROYO GUITARD, DAVID ANGEL');
execute insertarjugadores('40975','BORREGO GONZALEZ, MARIA JOSE');
execute insertarjugadores('40995','CEJUDO RODRIGUEZ, FRANCISCO JOSE');
execute insertarjugadores('41931','GARCIA SANCHEZ, JOSE ANGEL');
execute insertarjugadores('42348','PLATERO DIEZ, ANTONIO');
execute insertarjugadores('43024','MUÑOZ MEDINA, RAFAEL');
execute insertarjugadores('43554','PIGOZZO, LUIGI CESARE');
execute insertarjugadores('43848','PINEDA SANCHEZ, FRANCISCO ASIS');
execute insertarjugadores('44425','HE, AIE');
execute insertarjugadores('45855','ESCANDELL BELLVER, BERNARDO');
execute insertarjugadores('45859','LI, GUANGMI');
execute insertarjugadores('47518','CORSI, MARCO EGIDIO');
execute insertarjugadores('48473','VILLEGAS GIRALDEZ, EDUARDO');
execute insertarjugadores('49054','BALLESTEROS RAMIREZ, JUAN CARLOS');
execute insertarjugadores('49669','CARRION JIMENEZ, JUAN LUIS');
execute insertarjugadores('50825','BORREGO GONZALEZ, JOSE DAVID');
execute insertarjugadores('52367','SANCHEZ PEÑALVER, GONZALO');
execute insertarjugadores('53711','CUENCA COT, EDUARDO');
execute insertarjugadores('53724','GUAN, WENHUI');
execute insertarjugadores('53828','REYES CALDERON, JOSE ANTONIO');
execute insertarjugadores('54498','FUENTES LOPEZ, FRANCISCO');
execute insertarjugadores('55901','NARROS LLUCH, MIGUEL OCTAVIO');
execute insertarjugadores('55914','ALVAREZ DE SOTOMAYOR REINA, AGUSTIN');
execute insertarjugadores('56558','RUIZ CARO, JOSE MANUEL');
execute insertarjugadores('56787','PAN, JUN');
execute insertarjugadores('57155','LOPEZ RUIZ, JOSE ANTONIO');
execute insertarjugadores('57332','GARCIA LORENTE, ISIDRO');
execute insertarjugadores('57971','RANGEL VELEZ, ESTEBAN');
execute insertarjugadores('59406','GARCIA BABON, FERNANDO');
execute insertarjugadores('59528','ROMERO MORENO, IGNACIO MANUEL');
execute insertarjugadores('59936','CERPA DOMINGUEZ, MANUEL');
execute insertarjugadores('60337','ACEVEDO MORENO, JOSE');
execute insertarjugadores('61282','CARMONA MARQUEZ, MANUEL JESUS');
execute insertarjugadores('62331','WANG, HONG');
execute insertarjugadores('62393','FERNANDEZ, ANTONIO ALFREDO');
execute insertarjugadores('63940','ESTEVE MURT, ANTONIO');
execute insertarjugadores('63968','FENG, JIAN');
execute insertarjugadores('64666','MARTINEZ LUCAS, JOAQUIN');
execute insertarjugadores('64850','WU, CHUNLAI');
execute insertarjugadores('65789','CASAL PEREZ, BORJA');
execute insertarjugadores('66032','POLO GUERRERO, ANTONIO');
execute insertarjugadores('66054','NUÑEZ ORFILA, FRANCISCO JAVIER');
execute insertarjugadores('67251','STEFAN, ION');
execute insertarjugadores('67545','REYES CALDERON, MANUEL');
execute insertarjugadores('67944','ALONSO ESPINAR, ISIDRO JESUS');
execute insertarjugadores('68435','LOPEZ DOVAO, MANUEL');
execute insertarjugadores('69101','HONG, XIAOJUN');
execute insertarjugadores('69103','AHMAD GONZALEZ, JAVIER NEDAL');
execute insertarjugadores('70376','WU, HAI');
execute insertarjugadores('70533','PAN, YONGZHONG');
execute insertarjugadores('71263','PARRADO GARCIA, JORGE');
execute insertarjugadores('71304','XIN, HUIYUN');
execute insertarjugadores('72273','PALOMEQUE OTERO, JUAN MANUEL');
execute insertarjugadores('72594','MEI, SHAOFANG');
execute insertarjugadores('73107','WEI, LIBIN');
execute insertarjugadores('73143','JIN, CHENG');
execute insertarjugadores('74665','ESPINAR AGUILAR, PABLO');
execute insertarjugadores('74704','MOYA FAGUNDO, RAUL');
execute insertarjugadores('75024','ZHAN, WANGSHENG');
execute insertarjugadores('75326','ESCAÑO VAZQUEZ, JORGE');
execute insertarjugadores('76081','BLANCO GONZALEZ, JOSE MANUEL');
execute insertarjugadores('76237','LLAMBIAS LLORENS, FRANCISCO');
execute insertarjugadores('76865','ROMERO DIAZ, RAMON');
execute insertarjugadores('77220','PAREJO CIDONCHA, AGUSTIN');
execute insertarjugadores('78176','RETAMAR MARTIN, FELIX');
execute insertarjugadores('78899','GARCIA TRIGO, JONATAN');
execute insertarjugadores('78977','MAKHLOUFI, ABDELAZIZ');
execute insertarjugadores('79502','GARCIA PEREZ, DAVID');
execute insertarjugadores('79572','BRAVO FRANCO, MARIA ANGELES');
execute insertarjugadores('81124','ZHU, BOLING');
execute insertarjugadores('81129','HU, YUNHENG');
execute insertarjugadores('81178','WU, ZONGGUANG');
execute insertarjugadores('81387','ANDRADE SANCHEZ, MANUEL CARLOS');
execute insertarjugadores('81491','DELGADO NAVARRO, JOAQUIN');
execute insertarjugadores('81712','LIN, HUARONG');
execute insertarjugadores('81838','EXPOSITO GOMEZ, MANUEL');
execute insertarjugadores('83453','SUN, HEPING');
execute insertarjugadores('84402','CLEMENTE GOMEZ, JESUS');
execute insertarjugadores('84405','WANG, WANSHENG');
execute insertarjugadores('84691','CHABAN NAVARRO, NASER');
execute insertarjugadores('86172','LOPEZ VAZQUEZ, JOSE LUIS');
execute insertarjugadores('86205','SANZ CORDOVILLA, JORGE');
execute insertarjugadores('88209','GIRALDEZ MARQUEZ, JOSE ANTONIO');
execute insertarjugadores('90207','RODRIGUEZ CARRETERO SANCHEZ, GUILLERMO');
execute insertarjugadores('91211','LI, XIGUAN');
execute insertarjugadores('91919','LEYVA MARTINEZ, JOSE');
execute insertarjugadores('92194','NOGALES HERNANDEZ, MIGUEL ANGEL');
execute insertarjugadores('92735','REYES DOMINGUEZ, VALERIANO');
execute insertarjugadores('93172','GARCIA MENDEZ, CARLOS DAVID');
execute insertarjugadores('94544','CHEN, XUECHAI');
execute insertarjugadores('95457','LLAMAS VELADO, LUIS ANGEL');
execute insertarjugadores('95482','MOYA XIMENEZ, JUAN LUIS');
execute insertarjugadores('97334','YANG, LIFEN');
execute insertarjugadores('97357','MORALES MARIN, JUAN FRANCISCO');
execute insertarjugadores('97692','YANG, RONG');
execute insertarjugadores('99216','CEBOLLADA SEBASTIAN, JOSE MANUEL');
execute insertarjugadores('99221','AGUILAR REY, SANTIAGO');
execute insertarjugadores('100260','PEDROTE MORALES, JAVIER');
execute insertarjugadores('101580','ORTIZ MORENO, JOSE MANUEL');
execute insertarjugadores('102606','LESPIAUC SAYA, JUAN PABLO');
execute insertarjugadores('102985','GARAY SANCHEZ, MARIA TERESA');
execute insertarjugadores('103112','VON AUGUST RUDICH, ISDELL PRIMROSE');
execute insertarjugadores('103116','DAZA GARCIA, CESAR');
execute insertarjugadores('103328','RETAMAR SANCHEZ, FRANCISCO');
execute insertarjugadores('103394','CASTRO SAINERO, JOSE ENRIQUE');
execute insertarjugadores('105113','FU, ZHENJUN');
execute insertarjugadores('105416','CINTAS VILLEGAS, ALEJANDRO');
execute insertarjugadores('105821','RINCON LEON, JOSE');
execute insertarjugadores('106398','CASTRO MARTIN, RUBEN');
execute insertarjugadores('106633','GONZALEZ MENA, ALVARO');
execute insertarjugadores('106719','CHEN, XIAOJUAN');
execute insertarjugadores('107123','CORDOBA GUTIERREZ, MIGUEL');
execute insertarjugadores('107463','CABALLERO BARRERA, LUIS MANUEL');
execute insertarjugadores('107633','XU, WENYI');
execute insertarjugadores('107634','ZHANG, QIUHUA');
execute insertarjugadores('107981','ROMERO ALCONCHEL, LUIS ALBERTO');
execute insertarjugadores('108504','GOMEZ GAVILAN, ROSA MARIA');
execute insertarjugadores('108552','MARTINEZ RAMOS, JOSE JUAN');
execute insertarjugadores('108677','SHA BAN AL DAJANI, ABDUL KAREEM MAHMOUD');
execute insertarjugadores('108678','ALEGRIA HERRERA, JACKELINE ZULEYCA');
execute insertarjugadores('109612','CHEN, KANGPING');
execute insertarjugadores('110598','WU, YIXIAO');
execute insertarjugadores('111604','ZHOU, ZUKANG');
execute insertarjugadores('112399','STEFAN, FLORIN');
execute insertarjugadores('112577','RUEDA CHECA, LUIS');
execute insertarjugadores('112730','GARCIA RUIZ, RICARDO');
execute insertarjugadores('113751','ZHAO, ZIJUN');
execute insertarjugadores('113870','SARABIA HAYA, CARLOS');
execute insertarjugadores('114108','ALDABA MUTILVA, JOSE LUIS');
execute insertarjugadores('114780','DEL AGUILA PEREZ, FRANCISCO');
execute insertarjugadores('116226','MOLINERO CARRASCO, ISMAEL');
execute insertarjugadores('116870','INFANTE MENDOZA, JUAN DIEGO');
execute insertarjugadores('118354','ZHAN, XIAOPING');
execute insertarjugadores('118367','CABRERA PALACIOS, DANIEL');
execute insertarjugadores('118634','ZHENG, YI');
execute insertarjugadores('119645','GUTIERREZ MORENO, JAVIER');
execute insertarjugadores('120209','ANERA RUIZ, RAFAEL');
execute insertarjugadores('120264','GARCIA RODRIGUEZ, MANUEL');
execute insertarjugadores('120364','SANCHEZ ROMERO, JOSE LUIS');
execute insertarjugadores('120371','PEREZ RUEDA, MANUEL');
execute insertarjugadores('120929','SOSA CABELLO, ALBERTO');
execute insertarjugadores('121576','KIZILCELIK, YUSUF');
execute insertarjugadores('122299','LIU, XIANG');
execute insertarjugadores('122372','GARCIA JURADO, ALEJANDRO');
execute insertarjugadores('122429','CARNERERO DE PABLO BLANCO, JESUS');
execute insertarjugadores('122685','SANCHEZ LOPEZ, FRANCISCO');
execute insertarjugadores('122689','CLAVIJO SALVATIERRA, FRANCISCO JOSE');
execute insertarjugadores('123252','GARCIA CEBRERO, JOSE MARIA');
execute insertarjugadores('123330','WU, JUN YONG');
execute insertarjugadores('123556','ALEKSANYAN, EDVARD');
execute insertarjugadores('124011','LIN, LIYONG');
execute insertarjugadores('124509','ABAD ANSELMO, RAFAEL');
execute insertarjugadores('124606','LOMBARDI, LUCIANO');
execute insertarjugadores('124652','DIAZ CHACON, MARIA CARMEN');
execute insertarjugadores('124653','CHACON ALVAREZ DE SOTOMAYOR, MARIA DE LA VICTORIA');
execute insertarjugadores('124732','NUCCI, CLAUDIO');
execute insertarjugadores('125597','MARTINEZ BELTRAN, SANTIAGO');
execute insertarjugadores('126335','PARRADO MARTINEZ, MANUELA');
execute insertarjugadores('126928','CHEN, LIN');
execute insertarjugadores('126930','YUAN, YONG');
execute insertarjugadores('126938','CARO BONILLA, TOMAS DOMINGO');
execute insertarjugadores('126950','VAZQUEZ ORIA, RAFAEL');
execute insertarjugadores('128148','GUARDEÑO TORRALBO, JUAN ANTONIO');
execute insertarjugadores('128195','BARONA ALVAREZ, JOSE MARIA');
execute insertarjugadores('128697','CONTRERAS RIOS, MARIA DEL ROCIO');
execute insertarjugadores('128977','ARAUJO LATORRE, ALVARO');
execute insertarjugadores('128978','GARCIA GIL, DAVID');
execute insertarjugadores('129380','ORTIZ ALBARRAN, JUAN ANTONIO');
execute insertarjugadores('129382','LINERO MARIN, JERONIMO');
execute insertarjugadores('129793','GOMEZ CIPRIAN, LUIS');
execute insertarjugadores('129895','TRISTAN HERRERA, DIEGO');
execute insertarjugadores('130058','PINEDA VILLA, FELIPE');
execute insertarjugadores('130061','MATUS GONZALEZ, ATENEO');
execute insertarjugadores('130195','CASTRO VAL, ISRAEL');
execute insertarjugadores('130214','WANG, ZENGLI');
execute insertarjugadores('130327','CAMPOS TORRES, JUAN ANTONIO');
execute insertarjugadores('131398','WU, SUZHEN');
execute insertarjugadores('131401','FRANCO DIEGUEZ, JOSE CARLOS');
execute insertarjugadores('132055','TROYA RODRIGUEZ, ANTONIO');
execute insertarjugadores('132609','URBANO SIERRA, FELIPE');
execute insertarjugadores('133330','BENITEZ COLON, SERGIO');
execute insertarjugadores('134152','DE LAS CUEVAS SANCHEZ DE IBARGÜEN, ALEJANDRO BARTOLOME');
execute insertarjugadores('135214','RIVERA PANTOJA, FRANCISCO JOSE');
execute insertarjugadores('135369','BARQUERO MARTIN, ALEJANDRO');
execute insertarjugadores('135581','GRANADOS LUQUE, ANTONIO');
execute insertarjugadores('135644','DORADO GONZALEZ, EDUARDO');
execute insertarjugadores('135702','CONSTANTIN, DAVID');
execute insertarjugadores('136258','CHACON JIMENEZ, ISMAEL');
execute insertarjugadores('136337','GOMEZ BARCELO, JOAQUIN');
execute insertarjugadores('136590','MORENO CAMPOS, GUMERSINDO MANUEL');
execute insertarjugadores('136951','AZCON NAVARRO, JOAQUIN ALEJANDRO');
execute insertarjugadores('136976','CALANCHE HERRERA, JARVIC VICENTE');
execute insertarjugadores('136983','RIVAS TORRES, JOAQUIN');
execute insertarjugadores('137192','DOMINGUEZ GODINO, EUGENIO');
execute insertarjugadores('137244','HERNANDEZ SOCORRO, JULIO');
execute insertarjugadores('137314','SALAMA, M ABDELKADER');
execute insertarjugadores('137888','DIEGUEZ RECACHA, ROGELIO');
execute insertarjugadores('137899','MARTINEZ NUÑEZ, VICENTE');
execute insertarjugadores('138209','RUIZ ALVAREZ, ALFONSO MARCELO');
execute insertarjugadores('138371','CHEN, HAO');
execute insertarjugadores('138849','GAONACH, PATRICK JEAN');
execute insertarjugadores('139557','MARIN ROS, CARLOS MANUEL');
execute insertarjugadores('140491','MAGRO MATILLA, JAVIER');
execute insertarjugadores('140822','RUIZ PEREZ, MOISES');
execute insertarjugadores('141286','HINCHADO MELENDEZ, FRANCISCO');
execute insertarjugadores('141342','LIAO, SUNZHONG');
execute insertarjugadores('141607','MESEGUER GONZALEZ, JOSE ANTONIO');
execute insertarjugadores('141785','BAFFEREAU, SEBASTIEN HENRI');
execute insertarjugadores('142027','GUO, MEIZHEN');
execute insertarjugadores('142064','ROMAN ALCAIDE, INOCENCIO ANTONIO');
execute insertarjugadores('142168','TORRES BUIGUES, XAVIER');
execute insertarjugadores('143515','ALGABA AVILA, RAFAEL');
execute insertarjugadores('143708','BALIÑAS DE LA CONCHA, MANUEL');
execute insertarjugadores('144139','LAHOZ RUANO, JUAN LEON');
execute insertarjugadores('144793','FIGUERAS MONTEL, JORDI');
execute insertarjugadores('144795','JAEN MORON, JULIO');
execute insertarjugadores('145259','PEÑUELA PABLOS, RAFAEL');
execute insertarjugadores('145703','FONTEYN, ROBERT AUGUST E');
execute insertarjugadores('145997','ESCODA TURBANY, JORGE');
execute insertarjugadores('146024','ORTEGA GUILLEN, CRISTOBAL');
execute insertarjugadores('146154','LEE, SEONG YONG');
execute insertarjugadores('146184','DEULOFEU LAZARO, GERARD');
execute insertarjugadores('146434','FERNANDEZ CABELLO, JUAN JESUS');
execute insertarjugadores('146438','CABALLERO LORA, JUAN');
execute insertarjugadores('147146','PACHECO LOBATO, DANIEL');
execute insertarjugadores('147546','ARGUEZ RUIZ, JUAN JESUS');
execute insertarjugadores('147549','ACOSTA DE LA ROSA, MODESTO');
execute insertarjugadores('147815','CALDERON VERA, ANTONIO MANUEL');
execute insertarjugadores('148101','LOPEZ PEREZ, CIPRIANO MANUEL');
execute insertarjugadores('148178','KERCUKU, EMILIO');
execute insertarjugadores('148346','ACQUISTAPACE, PASQUALE');
execute insertarjugadores('148387','ZAMFIR, ELVIS');
execute insertarjugadores('148409','LOBATO ALVAREZ, BERNAROO');
execute insertarjugadores('149014','PARDO GARCIA, JUAN MANUEL');
execute insertarjugadores('149024','ROMERO CABEZA, VICTOR MANUEL');
execute insertarjugadores('149175','FERNANDEZ CABANILLAS, ABRAHAM');
execute insertarjugadores('149671','GALISTEO MUÑOZ, NANUEL');
execute insertarjugadores('149790','MEJIAS ALVAREZ, SANDRA');
execute insertarjugadores('149823','XIE, ZHONGYAO');
execute insertarjugadores('149824','XIE, ZHONGGUAN');
execute insertarjugadores('150222','PAN, QIANG');
execute insertarjugadores('150292','LOZANO DIEGUEZ, MANUEL JESUS');
execute insertarjugadores('150363','CINTRA VIEGAS, JASON');
execute insertarjugadores('150425','FAN, CHUNHUA');
execute insertarjugadores('150447','MAINI, ALFREDO');
execute insertarjugadores('150469','CAMPILLO CRESPO, ALEJANDRO JOSE');
execute insertarjugadores('150603','RODRIGUEZ CARRERA, MANUEL');
execute insertarjugadores('150638','BARBERA GALLARDO, MANUEL');
execute insertarjugadores('150666','HUA, KUIZHANG');
execute insertarjugadores('150719','WANG, CHIYAO');
execute insertarjugadores('150826','DAI, JIANKE');
execute insertarjugadores('150969','DUCAY DE LA RIVA, JOAQUIN');
execute insertarjugadores('151085','LIU, CHANGHAI');
execute insertarjugadores('151183','GARRIDO RODRIGUEZ, ANDRES MANUEL');
execute insertarjugadores('151210','VIDAL MENGUAL, JAVIER');
execute insertarjugadores('151264','VENEZIANO BROCCIA, MASSIMO');
execute insertarjugadores('151284','GABALDON BOTELLA, ROGELIO');
execute insertarjugadores('151289','CHEN, WEIXING');
execute insertarjugadores('151290','YI, ZHENG');
execute insertarjugadores('151387','PAN, JINLONG');
execute insertarjugadores('151564','DA CRUZ NETO MESTRE, FERNANDO MANUEL');
execute insertarjugadores('151567','MARTIN JAEN, EMILIO');
execute insertarjugadores('151568','GALVAN CACELA, JUAN CARLOS');
execute insertarjugadores('151574','DOMINGOS TOMAS LOPES, ANTONI M');
execute insertarjugadores('151582','HUELVA GARCIA, MARCELO');
execute insertarjugadores('151601','POGGI, GAETAN EMILE');
execute insertarjugadores('151636','PARK, JUNGMAN');
execute insertarjugadores('151685','SIERCO JARQUE, ALBERTO');
execute insertarjugadores('151812','KHAZARDJIAN, YERVANT');
execute insertarjugadores('151821','YE, YINHU');
execute insertarjugadores('151856','ZHOU, HUIYI');
execute insertarjugadores('152050','CERDESCHI, MASSIMILIANO');
execute insertarjugadores('152058','MARTINY, ROBERT FRANCOIS');
execute insertarjugadores('152165','YANG, HANG');
execute insertarjugadores('152174','ZHANG, XIANKUN');
execute insertarjugadores('152206','CHEN, JIANJUN');
execute insertarjugadores('152208','ADAN GARRIDO, ANTONIO');
execute insertarjugadores('152377','RAVE, ROY');
execute insertarjugadores('152378','GERNEIL O, LORNE');
execute insertarjugadores('152464','RAVE, LEIAT');
execute insertarjugadores('152489','KRASOVSCHI-MUREA, STEFAN');
execute insertarjugadores('152524','FORTAS, KHEMISSI');
execute insertarjugadores('152639','LI, WEIDONG');
execute insertarjugadores('152660','RONG, XIN');
execute insertarjugadores('152662','ZHANG, LI');
execute insertarjugadores('152740','ZAFRA CRESPIN, ANTONIO JESUS');
execute insertarjugadores('152781','LI, FANG');
execute insertarjugadores('152856','PEREZ MUIÑO, JOSE ANTONIO');
execute insertarjugadores('152871','LIN, CHI HUNG');
execute insertarjugadores('153036','VILLALONGA PONS, PEDRO');
execute insertarjugadores('153043','BLEWIS, RICHARD MICHAEL');
execute insertarjugadores('153046','ANTHONY, SCOTT MICHAEL');
execute insertarjugadores('153064','GARCIA SANCHEZ, SAMUEL');
execute insertarjugadores('153083','TUDOR, FLORENTIN-OCTAVIAN');
execute insertarjugadores('153091','SALVATORE, MARIO');
execute insertarjugadores('153211','IBRAHIM, FARUK');
execute insertarjugadores('153215','VINALS FARRES, SANTIAGO');
execute insertarjugadores('153222','BAKHASHAB, KHALID');
execute insertarjugadores('153227','XIAO, JUN');
execute insertarjugadores('153309','OZEL, SAMET KURSAD');
execute insertarjugadores('153366','LIU, DONGDONG');
execute insertarjugadores('153380','HU, CHUNHUA');
execute insertarjugadores('153381','TANG, WEIDONG');
execute insertarjugadores('153383','YANG, WEIDONG');
execute insertarjugadores('153384','GAO, YUEQIN');
execute insertarjugadores('153394','MANSOURI, YASSINE');
execute insertarjugadores('153434','DUMITRU, DANIEL');
execute insertarjugadores('153440','VAHID, MOHADJERI');
execute insertarjugadores('153570','PEREZ MARTINEZ, ALVARO');
execute insertarjugadores('153624','MANCINELLI, MASSIMO');
execute insertarjugadores('153639','MARASCIO, FRANCESCO');
execute insertarjugadores('153641','CUTULI, DANIELE');
execute insertarjugadores('153681','CAMPOBASSO, LUCIANO');
execute insertarjugadores('153744','CHAMMAK, ABDERRAHIM');
execute insertarjugadores('153797','PALENZUELA TEJERO, JAIME');
execute insertarjugadores('153943','NEBBIA, CLAUDIO LUIS');
execute insertarjugadores('153945','CIARDI, NICOLA');
execute insertarjugadores('153948','GHIRELLI, PIERPAOLO');
execute insertarjugadores('153949','VINCI, NICOLA');
execute insertarjugadores('153951','DEPERU, GIOVANNI MARIA');
execute insertarjugadores('153952','GONZALEZ MAYA, DANIEL');
execute insertarjugadores('153958','DI GREGORIO, MAURICIO');
execute insertarjugadores('153967','PASHKEVICH, ANDREY');
execute insertarjugadores('153969','BOVER GAGO, JOSE MANUEL');
execute insertarjugadores('153970','CABANILLAS GOMEZ, ALEJANDRO');
execute insertarjugadores('153972','TANVALD, ROLF HARRY');
execute insertarjugadores('154019','ZHOU, JIANHUA');
execute insertarjugadores('154085','RICO CASTRO, FRANCISCO MANUEL');
execute insertarjugadores('154102','RITCHER, ALAIN');
execute insertarjugadores('154103','KUO, PO KUAN');
execute insertarjugadores('154104','PALOMARES MORRON, DAVID');
execute insertarjugadores('154106','ZHOW YE, RICARDO FILIPE');
execute insertarjugadores('154115','LOZANO, KATY');
execute insertarjugadores('154116','LOZANO GRAVINA, JUAN CLAUDIO');
execute insertarjugadores('154131','AHMED AHMED, MUSTAFA');
execute insertarjugadores('154132','SAADEH, SHERIF NABIL IBRAHIM');
execute insertarjugadores('154133','SARMIENTO FEIJOO, CARLOS JOSE');
execute insertarjugadores('154221','ALVAREZ RANERO, JAVIER');
execute insertarjugadores('154232','ALMUTAIRI, MESHARI F M D J');
execute insertarjugadores('154247','MAKHOUL, ROBERT MICHAEL');
execute insertarjugadores('154310','VAN ENGELEN, SERVAAS PAULUS HENDERIKUS');
execute insertarjugadores('154311','GUSSENHOVEN, KAREL PIETER');
execute insertarjugadores('154374','ABBASI, DARIUSH');
execute insertarjugadores('154399','TSANG, TSZ SHUN');
execute insertarjugadores('154402','MESSOUS, RACHID');
execute insertarjugadores('154429','VARAKANTHAM, AKILESH REDDY');
execute insertarjugadores('154435','RUIZ PAZ, FERNANDO');
execute insertarjugadores('154443','COLI, MARCO');
execute insertarjugadores('154461','PEI, DONGNA');
execute insertarjugadores('154500','DENIZKUSU, AHMET OGUZ');
execute insertarjugadores('154582','SELIGNAN, JEAN-LUC, MAURICE');
execute insertarjugadores('154595','AKKINENI, AKHIL');
execute insertarjugadores('154597','RAGHU CHOWDARAPU, RATUL');
execute insertarjugadores('154606','CHUVAS, PEDRO, HORACIO');
execute insertarjugadores('154617','MAURIZIO, DANESI');
